package relativity.message;

public enum Type { 
	ALL,
	ZOOM_CHANGED, 
	OFFSET_CHANGED,
	WINDOW_CHANGED,
	DIAGRAM_LOADED,
	NEW_DIAGRAM,
	WORLD_LINE_ADDED,
	WORLD_LINE_DELETED,
	WORLD_LINE_CHANGED,
	EVENT_ADDED,
	EVENT_DELETED,
	EVENT_CHANGED,
	FRAME_ADDED,
	FRAME_DELETED,
	FRAME_VELOCITY_CHANGED, 
	BASE_FRAME_CHANGED, 
	BACKGROUND_UPDATED
	
}
